### ISSUE TITLE
Server part breaks down

### ISSUE THREAD

**Issue by zlatnaspirala** [zlatnaspirala/visual-ts-game-engine#16]
Log : 

```
MultiRTC3: new client.
+++++++++++++++++11+++++++++++++++++
/var/applications/vts-server/rtc/broadcaster.js:58
            res.writeHead(200, headers);
            ^

ReferenceError: res is not defined
    at Server.serverHandler (/var/applications/vts-server/rtc/broadcaster.js:58:13)
    at Server.<anonymous> (/var/applications/vts-server/node_modules/engine.io/lib/server.js:470:22)
    at Server.<anonymous> (/var/applications/vts-server/node_modules/socket.io/lib/index.js:343:16)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:652:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by zlatnaspirala** [comment]
Mistake .
